// <auto-generated />
using Gestion_Compte_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Compte_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240821145150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Gestion_Compte_App.Models.Intervenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JoursHommes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("QualificationIntervention")
                        .HasColumnType("REAL");

                    b.Property<double>("TarifJournalier")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Intervenants");
                });
#pragma warning restore 612, 618
        }
    }
}
